apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadnxxj9510-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadnxxj9510-tenant-component
    app.kubernetes.io/part-of: loadnxxj9510-tenant-app
  name: loadnxxj9510-tenant-component
  namespace: loadnxxj9510-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadnxxj9510-tenant-component
    weight: null
status: {}
